### ISSUE TITLE
[Feature Request] git add -i (patch)

### ISSUE THREAD

**Issue by Nandiin** [akonwi/git-plus#484] opened 2016-07-13 07:04 UTC
Is there any plan to implement interactive add? with that I can add hunks interactively

**Comment by superdump** [comment] 2016-08-02 08:13
Related to / duplicate of #246

**Closed** 2016-11-07 19:29 UTC
Labels: duplicate

**Comment by akonwi** [comment] 2016-11-07 21:55
The Stage Hunk command provides this. It could use some polishing I think but that is the interactive add command.
