### ISSUE TITLE
Problem with signed commits

### ISSUE THREAD

**Issue by eliabieri** [akonwi/git-plus#456] opened 2016-06-01 22:17 UTC
When I want to commit a signed commit I get the following error

`gpg: cannot open /dev/tty: Device not configured
error: gpg failed to sign the data
fatal: failed to write commit object`

**Comment by niij** [comment] 2016-06-10 23:27
This appears to be a duplicate of Issue #427.  There is a workaround on that issue thanks to @svagi.  Reposting here:
    echo "no-tty" >> ~/.gnupg/gpg.conf

**Comment by akonwi** [comment] 2016-11-04 18:31
Thanks @niij

**Closed by akonwi** 2016-11-04 18:31 UTC
