### ISSUE TITLE
pre-push hook runs twice

### ISSUE THREAD

**Issue by SlimeQ** [akonwi/git-plus#410] opened 2016-02-29 23:25 UTC
i set a simple pre-push hook that plays an audio file. when pushing from git-plus the script is run twice. while this does not affect me terribly i can imagine a situation where somebody might not want a more important hook to be run twice

**Comment by akonwi** [comment] 2016-11-01 19:57
Is this still a recurring issue? I can't reproduce it. I'm going to close it and if it is still a problem we can reopen it.

**Closed by akonwi** 2016-11-01 19:57 UTC
