### ISSUE TITLE
Uncaught TypeError: Cannot read property 'charAt' of undefined

### ISSUE THREAD

**Issue by Junmini** [akonwi/git-plus#166] opened 2015-03-10 18:27 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.187.0
**System**: Mac OS X 10.10
**Thrown From**: [git-plus](https://github.com/akonwi/git-plus) package, v4.4.8

### Stack Trace

Uncaught TypeError: Cannot read property 'charAt' of undefined

```
At path.js:463

TypeError: Cannot read property 'charAt' of undefined
  at Object.posix.isAbsolute (path.js:463:14)
  at Object.posix.normalize (path.js:445:26)
  at DefaultDirectoryProvider.module.exports.DefaultDirectoryProvider.directoryForURISync (/Users/junminprk/Downloads/Atom.app/Contents/Resources/app/src/default-directory-provider.js:15:26)
  at Project.module.exports.Project.addPath (/Users/junminprk/Downloads/Atom.app/Contents/Resources/app/src/project.js:279:87)
  at Project.module.exports.Project.setPaths (/Users/junminprk/Downloads/Atom.app/Contents/Resources/app/src/project.js:253:14)
  at Project.module.exports.Project.setPath (/Users/junminprk/Downloads/Atom.app/Contents/Resources/app/src/project.js:263:19)
  at git.cmd.stdout (/Users/junminprk/.atom/packages/git-plus/lib/models/git-init.coffee:9:20)
  at exit (/Users/junminprk/.atom/packages/git-plus/lib/git.coffee:26:7)
  at BufferedProcess.triggerExitCallback (/Users/junminprk/Downloads/Atom.app/Contents/Resources/app/src/buffered-process.js:63:47)
  at /Users/junminprk/Downloads/Atom.app/Contents/Resources/app/src/buffered-process.js:77:18
  at Socket.<anonymous> (/Users/junminprk/Downloads/Atom.app/Contents/Resources/app/src/buffered-process.js:150:18)
  at Socket.emit (events.js:138:20)
  at Pipe.close (net.js:477:12)

```

### Commands

```
     -3:03.8 git-plus:add (atom-text-editor.editor)
     -3:01.1 git-plus:add-all (atom-text-editor.editor)
     -2:58.6 git-diff:move-to-next-diff (atom-text-editor.editor)
     -2:53.5 open-on-github:copy-url (atom-text-editor.editor)
     -0:35.6 settings-view:open (atom-text-editor.editor)
     -0:03.9 git-plus:menu (div.settings-view.pane-item)
     -0:01.9 core:backspace (atom-text-editor.editor.mini)
     -0:01.2 core:confirm (atom-text-editor.editor.mini)
```

### Config

```json
{
  "core": {
    "projectHome": "https://Cooing@bitbucket.org/cooingteam/cooing-web.git"
  },
  "git-plus": {}
}
```

### Installed Packages

```coffee
# User
git-plus, v4.4.8

# Dev
No dev packages
```

**Comment by akonwi** [comment] 2015-03-16 22:25
Can you list the steps to reproduce the error?

**Comment by clarkwinkelmann** [comment] 2015-05-07 12:51
Same error here with `Atom 0.196.0` on `Ubuntu 14.04`. Having problems with Atom and my proxy I cloned your repo in my `.atom/packages` repertory, checked out `tags/v4.5.0` and `npm install` in the directory. When typing `CTRL+SHIFT+H` then `git status` in the popup, then `ENTER`, the error appears.  There's probably a step missing in my installation, which causes the error...

Here's the error report:

**Atom Version**: 0.196.0
**System**: linux 3.13.0-52-generic
**Thrown From**: 'git-plus' package, vundefined

### Stack Trace

Uncaught TypeError: Cannot read property 'charAt' of undefined

```
At path.js:440

TypeError: Cannot read property 'charAt' of undefined
    at Object.posix.isAbsolute (path.js:440:14)
    at Object.posix.normalize (path.js:422:26)
    at DefaultDirectoryProvider.module.exports.DefaultDirectoryProvider.directoryForURISync (/usr/share/atom/resources/app.asar/src/default-directory-provider.js:15:26)
    at Project.module.exports.Project.addPath (/usr/share/atom/resources/app.asar/src/project.js:253:87)
    at Project.module.exports.Project.setPaths (/usr/share/atom/resources/app.asar/src/project.js:230:14)
    at Project.setPath (/usr/share/atom/resources/app.asar/src/project.js:588:19)
    at git.cmd.stdout (/home/clark/.atom/packages/git-plus/lib/models/git-init.coffee:16:29)
    at exit (/home/clark/.atom/packages/git-plus/lib/git.coffee:35:9)
    at triggerExitCallback (/usr/share/atom/resources/app.asar/src/buffered-process.js:213:47)
    at /usr/share/atom/resources/app.asar/src/buffered-process.js:220:18
```

### Commands

```
     -0:05.7.0 git-plus:menu (atom-text-editor.editor)
     -0:03.3.0 core:backspace (atom-text-editor.editor.mini)
     -0:02.1.0 core:confirm (atom-text-editor.editor.mini)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-light-ui",
      "one-light-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
git-plus2, v4.5.0
language-blade, v0.13.0

# Dev
No dev packages
```

**Comment by akonwi** [comment] 2015-05-13 21:57
@clarkwinkelmann I'm having trouble understanding what happened. Were you using the `git status` command when this error was thrown? If so, I'm concerned about why the `git-init` command is in the stack trace.

**Comment by clarkwinkelmann** [comment] 2015-05-14 21:05
I checked again, but I described right.

1. I start Atom
2. I press CTRL+SHIFT+H
3. I type "git status"
4. Plugin crash with the trace I have posted above

After more testing, I see this error triggers whenever I type a non-existing command or a command that is not available in the current context (Just starting Atom places me in my home folder so no `git-status` there)

So more flexible steps:
1. Start Atom, open nothing or a file or a folder, etc...
2. Press CTRL+SHIFT+H
3. Type something that has no autocomplete (like `gbdzfgzsvfzefv` or `status` in a non-git folder)
4. Plugin crashes, and the trace is always the exact same (with the `git-init.coffee` inside)

**Comment by akonwi** [comment] 2015-05-16 19:14
That is odd. If you're in a non-git folder, the menu should only have the `init` command regardless of what you type. I'm also not getting the behavior you're experiencing on my machine.

I've been working on a new version to accompany the atom 1.0.0 release. It's in the branch of this repo named '1.0.0'. Clone that branch and give it a shot. I could use the feedback because I'm preparing to publish it soon and it has a couple big changes.

**Comment by clarkwinkelmann** [comment] 2015-05-22 06:22
I forgot to say that it's when I press ENTER that the addon crashes ^^

I've tested your 1.0.0 branch, it's not possible anymore to type something invalid as the autocomplete always gives the closer match (even `thiscommanddoesnotexists` is executed as `Checkout Current File`). So no idea if it's really fixed internally but at least you can't crash the addon just by typing junk like I did before.

**Comment by akonwi** [comment] 2015-05-26 00:06
Yea I assumed it was when you pressed enter that it would crash. 

The behavior you're experiencing in 1.0.0 is what I've always experienced and intended. Even if the filter didn't give you an option matching what you typed, then nothing should happen when you press enter.

Anyway, I'm glad this isn't an issue anymore on the 1.0.0 branch. That branch will become the published version within the next week

**Closed** 2015-08-05 21:56 UTC
