### ISSUE TITLE
Git Plus will not push

### ISSUE THREAD

**Issue by NickChamberlin** [akonwi/git-plus#518] opened 2016-09-26 06:08 UTC
![giterrorhelp](https://cloud.githubusercontent.com/assets/4814476/18824144/b4773460-8374-11e6-8cfd-a857e79167b9.png)

That's the error message I get. I've exhaustively gone through everything I can find on the internet and nothing is fixing the issue. I can see my commits in the GitHub windows app, but I have to go into the GitHub windows app if I actually want to push my commits to GitHub.com. I'm new to GitHub, I've found others with the same problem, but no answers on how to fix it.

**Comment by jonomacx** [comment] 2016-10-13 21:02
Is this a duplicate of #502 ?

**Comment by akonwi** [comment] 2016-11-07 20:39
Check out https://github.com/akonwi/git-plus/issues/224. The last comment there might be your solution

**Closed by akonwi** 2016-11-07 20:39 UTC
