### ISSUE TITLE
Pushing not working on LINUX

### ISSUE THREAD

**Issue by ceciliassis** [akonwi/git-plus#555] opened 2016-11-18 13:09 UTC
-----------------

Since I've installed this plugin (which i love), I can't push.
Steps to reproduce:

1. Type crtl+shift+h
2. Push
3. No window of prompt shows up. The error: 
![screenshot from 2016-11-18 11-09-07](https://cloud.githubusercontent.com/assets/9968803/20431122/825a20a2-ad7f-11e6-8deb-5768640a9e4e.png)

**Comment by akonwi** [comment] 2016-11-21 16:20
Which window of prompt are you referring to? Did you expect to be prompted for your username/password? If so, that won't happen. 

The package currently favors an ssh setup that doesn't expect to be prompted for credentials in order to push/pull, .etc. Github has a guide to help you set that up [here](https://help.github.com/articles/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent/)

**Comment by akonwi** [comment] 2016-12-01 02:12
I'm marking this as a duplicate of #224

**Closed by akonwi** 2016-12-01 02:12 UTC
