### ISSUE TITLE
[QUESTION]I cant seem to push

### ISSUE THREAD

**Issue by clang676** [akonwi/git-plus#550] opened 2016-11-17 20:56 UTC
I have github install, i set my path environment variable. i can commit using git-plus and i see in github that it is actually committing. However when i go to push it throws an error:

githun --credentials get: github: command not found
bash /dev/tty: No such device or address
error: failed to execute prompt script (exit code 1)
fata: could not read Username for 'https://github.com': Invalid argument

**Comment by akonwi** [comment] 2016-11-17 21:03
I think this is a duplicate of #413. The solution is https://github.com/akonwi/git-plus/issues/413#issuecomment-223413038

**Closed by akonwi** 2016-11-17 21:03 UTC
