### ISSUE TITLE
Git Push not working on Win 7

### ISSUE THREAD

**Issue by dmase44** [akonwi/git-plus#314] opened 2015-11-08 21:53 UTC
The git-plus package works great for the local repos. I can use all commands except push. My .ssh is in order. I get this error:

bash: /dev/tty: No such devise or address
error: failed to execute prompt script (exit code 1)
fatal: could not read Username for 'https://github.com' : Invalid argument
about.html 1:1

I don't get a prompt for the username or password I get from my other CLI's 

Your help will be appreciated, Dave

**Comment by akonwi** [comment] 2015-11-11 01:09
If you're getting a prompt each time in the command line, then ssh is setup completely. Pushing isn't working in the package because the child process for the command is halted at the need for you to enter your credentials. Make sure git is trusted through ssh. [This page](https://help.github.com/articles/generating-ssh-keys/) may be helpful

**Comment by dmase44** [comment] 2015-11-11 20:36
Thank you Akonwi for your response.

 

I had previously followed all the steps in the link you sent. I however generated new keys and followed all the steps without any issues and it went like clockwork including caching the password. The only change from the previous config is the error message.

 

Permission denied (publickey)

Fatal: Could not read from remote repository.

Please make sure you have the correct access rights and the repository exists.

 

I have 5 CLI’s: ConEmu with Ruby, ConEmu set to Shell, Git Bash, Git CMD, Git Shell plus Git GUI and and GitHub Desktop that have no ssh issues of any kind. The last two I don’t use. I clone using ssh occasionally without any problems.

 

I use the Git-Plus working with the local repos often and it works great but keep a CLI open for remote. This works for me now as I’m not going to install putty or other workarounds for this only ssh issue I have.

 

Thanks for the Git-Plus package and hopefully a windows dev will chime in and contribute to the ssh issues on Window in the near future.  

 

Dave

**Comment by akonwi** [comment] 2015-11-12 01:47
There are various issues opened by windows users about ssh problems. I wish I could be  more helpful in that area. If you search the issues for `ssh` and `windows`, you'll find what other users have posted and there are also solutions that some users have come across

**Comment by akonwi** [comment] 2015-11-13 00:19
Dave, I've come across something that may remedy the problem for you. Check out [git's credential store](https://git-scm.com/docs/git-credential-store) This might save you from needing to enter credentials

**Comment by akonwi** [comment] 2016-12-09 02:30
Marking as a duplicate of #224

**Closed by akonwi** 2016-12-09 02:30 UTC
