### ISSUE TITLE
Linux, OSX: " Invalid refspec '[object Object]' " - pull using rebase

### ISSUE THREAD

**Issue by jaimefortega** [akonwi/git-plus#332] opened 2015-11-21 02:35 UTC
I've tried to use the "pull using rebase" option from the menu, but I get the following error at the Atom's embedded Output Console:

fatal: Invalid refspec '[object Object]'

Also, it shows an empty list. It looks like that this happens only in the Linux version of Atom, because it works in the Windows version. I found this weird since I can push to my remote master branch without a problem. This also happens with "pull".

If I choose the "rebase" option from the menu, it shows the branches.

![git_plus_pull_bug](https://cloud.githubusercontent.com/assets/2206328/11316448/23aefd8c-8fe6-11e5-8396-4af64f61ec97.png)
[UPDATE]
It looks like that this happens in OSX too.

**Comment by igorsousa-b** [comment] 2015-11-23 15:32
I'm having the same issue, but with both regular git pull and git pull using rebase.

**Comment by jaimefortega** [comment] 2015-11-24 02:13
I also have a problem with just pull.

**Comment by Siilwyn** [comment] 2015-11-26 10:37
Confirmed at Ubuntu 14.04. Both git pull and git pull using rebase.

**Comment by uZer** [comment] 2015-12-01 14:23
Hi,
Same issue here
Atom 1.2.4 + Plugin git-plus 5.6.6
Windows 10
git 2.6.3.windows.1

Regards,

**Comment by teefax** [comment] 2015-12-07 11:54
A possible fix for this should be in #342

**Comment by igorsousa-b** [comment] 2015-12-09 09:01
Since 5.6.10, it now pulls but does so twice every time.

**Comment by jaimefortega** [comment] 2015-12-09 18:40
That's strange. In my case, it pulls just once. Are you using the 1.2.4 version of Atom? I've also reinstalled my entire OS, because I had a problem with my HDD. Now, everything works fine. Maybe it's pulling from two branches.

**Closed** 2015-12-09 18:44 UTC

**Comment by jaimefortega** [comment] 2015-12-09 18:47
This bug was fixed in git-plus 5.6.10. I'm closing the issue.
